title: [SNP and genotype calling]
subtitle: [Advanced Data Analysis - Introduction to NGS data analysis]

navigation: 2

sections: [
    ['setup', 'Initial setup'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts']
]
